from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime

def format_content(text):

    lines = text.split("\n")

    formatted = []

    for line in lines:

        line = line.strip()

        if not line:
            continue

        if line.startswith("-"):

            formatted.append(
                f"• {line[1:].strip()}"
            )

        else:

            formatted.append(line)

    return "<br/>".join(formatted)

def generate_pdf_report(
    ats_result,
    ai_analysis,
    interview_questions,
    roadmap,
    output_path="report.pdf"
):

    doc = SimpleDocTemplate(output_path)

    styles = getSampleStyleSheet()

    elements = []

    # ==========================
    # TITLE
    # ==========================

    elements.append(
        Paragraph(
            "AI Resume Analyzer Report",
            styles["Title"]
        )
    )

    elements.append(
        Paragraph(
            f"Generated on: {datetime.now().strftime('%d %B %Y')}",
            styles["BodyText"]
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    # ==========================
    # ATS SCORE
    # ==========================

    elements.append(
        Paragraph(
            "ATS Score Summary",
            styles["Heading1"]
        )
    )

    final_score = ats_result.get(
        "final_ats_score",
        "N/A"
    )

    elements.append(
        Paragraph(
            f"<b>Overall ATS Score:</b> {final_score}%",
            styles["Heading2"]
        )
    )

    elements.append(
        Spacer(1, 10)
    )

    # ==========================
    # ATS TABLE
    # ==========================

    table_data = [
        ["Category", "Score"]
    ]

    for key, value in ats_result.items():

        table_data.append(
            [
                key.replace("_", " ").title(),
                str(value)
            ]
        )

    ats_table = Table(
        table_data,
        colWidths=[250, 120]
    )

    ats_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.black),

                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
            ]
        )
    )

    elements.append(ats_table)

    elements.append(
        Spacer(1, 20)
    )

    # ==========================
    # PAGE BREAK
    # ==========================

    elements.append(PageBreak())

    # ==========================
    # AI ANALYSIS
    # ==========================

    elements.append(
        Paragraph(
            "AI Resume Analysis",
            styles["Heading1"]
        )
    )

    elements.append(
        Paragraph(
            format_content(ai_analysis),
            styles["BodyText"]
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    # ==========================
    # INTERVIEW QUESTIONS
    # ==========================

    elements.append(
        Paragraph(
            "Interview Questions",
            styles["Heading1"]
        )
    )

    elements.append(
        Paragraph(
            format_content(interview_questions),
            styles["BodyText"]
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    # ==========================
    # PAGE BREAK
    # ==========================

    elements.append(PageBreak())

    # ==========================
    # ROADMAP
    # ==========================

    elements.append(
        Paragraph(
            "Learning Roadmap",
            styles["Heading1"]
        )
    )

    elements.append(
        Paragraph(
            format_content(roadmap),
            styles["BodyText"]
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    # ==========================
    # FOOTER
    # ==========================

    elements.append(
        Paragraph(
            "Generated by AI Resume Analyzer & Interview Coach",
            styles["Italic"]
        )
    )

    doc.build(elements)

    return output_path